#!/opt/postconfirm/bin/python2

## Script to insert Resent-From and Resent-To headers into emails received via stdin.
##
## The script scans for either an existing Resent-* header, or the end of the headers
## as signified by a CRLF.  When one or the other is found, the Resent-From and
## Resent-To headers inserted above the target line.
## 
## This results in our Resent-* headers being prepended to any existing Resent-*
## headers as per section 3.6.6 of RFC 2822, or inserted at the end of the headers
## if there are no previous Resent-* headers.

## Import the sys module so we can read command line arguments
import sys

## Initialize the flag
found = 0

def expandDraft(draftname):
    files = ["/etc/postfix/draft-virtual","/etc/postfix/group-virtual"]
    result=""
    for fn in files:
    	try:	
		with open(fn,'r') as f:
    			for line in f:
    				lineparts = line.split('@')
    				if lineparts[0] == draftname:
    					f.close()	
					emails = line.replace(draftname,"")
    					emails = emails.replace('@virtual.ietf.org','')
    					return emails.strip()
    	except:
		f.close()
		# A file error has occurred
		# return an empty string, so the script continues to output the message 
		return "" 	
    return ""

# get the expanded addresses
try:
	expandedAddresses = expandDraft(sys.argv[1])
	draftname = sys.argv[1]
except:
	expandedAddresses = ""
	draftname=""

# if there are no expanded addresses, set the found flag to prevent further testing

if expandedAddresses == "":
	found = 1

for line in sys.stdin:
    try:
	if found == 0:
			if not line.strip(): #First blank line is the end of headers, insert
                                        print """Resent-From: <alias-bounces@ietf.org>"""
                                        print """Resent-To: %s""" % expandedAddresses
                                        #print """X-IETF-Alias: %s""" % draftname
					found=1
					print line,
			elif line[0:7] == "Resent-": #If there is a Resent-* header already, prepend ours
                                        print """Resent-From: <alias-bounces@ietf.org>"""
                                        print """Resent-To: %s""" % expandedAddresses
                                        #print """X-IETF-Alias: %s""" % draftname
					found=1
					print line,
			else:
				print line,

			
	else:
                                print line,
    except:
	continue
