#!/bin/sh

# run pctests
set -v

# forward to group
./pctest.py -f johnl@taugh.com confirm blurch-chairs@ietf.org < testmsg1 > tmout1 && diff testmsg1 tmout1

# forward to list
#./pctest.py -f johnl@taugh.com confirm blurch@ietf.org < testmsg4 > tmout4 && diff testmsg4 tmout4

# no rewrite
#./pctest.py -f johnl@taugh.com dmarc-rewrite blurch@ietf.org < testmsg2 > tmout2 && diff testmsg2 tmout2

# do rewrite

./pctest.py -f johnl@examp1e.com dmarc-rewrite blurch@ietf.org < testmsg3 > tmout3 && diff testmsg3 tmout3

./pctest.py -f johnl@examp1e.com confirm blurch@ietf.org < testmsg3> tmout3a && diff testmsg3 tmout3a

