#!/bin/sh

# run pctests
set -v

# forward to group, dkim should be ok
if ./pctest.py -f johnl@taugh.com confirm blurch-chairs@ietf.org < testmsg1 > tmout1
then
 diff testmsg1 tmout1
 dkimverify < tmout1
fi

# no rewrite, DKIM should be OK
if ./pctest.py -f johnl@taugh.com dmarc-rewrite blurch@ietf.org < testmsg2 > tmout2
then
  diff testmsg2 tmout2
  sed -e '/^===/d' tmout2 | dkimverify
fi

# do rewrite, OK to rewrap
if ./pctest.py -f johnl@examp1e.com dmarc-rewrite blurch@ietf.org < testmsg3 > tmout3
then
 diff testmsg3 tmout3
fi

# list with archive, don't rewrite
if ./pctest.py -f johnl@examp1e.com confirm ietf@ietf.org < testmsg4> tmout4a
then
 diff testmsg4 tmout4a
fi

# lsit without archive
if ./pctest.py -f johnl@examp1e.com confirm iesg@ietf.org < testmsg5> tmout5a
then
 diff testmsg5 tmout5a
fi
