apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postconfirm.fullname" . }}
  labels:
    {{- include "postconfirm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "postconfirm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postconfirm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postconfirm.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.postconfirm.database.host.existingSecretName . }}
                  key: {{ tpl .Values.postconfirm.database.host.existingSecretKey . }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.postconfirm.database.db_name.existingSecretName . }}
                  key: {{ tpl .Values.postconfirm.database.db_name.existingSecretKey . }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.postconfirm.database.user.existingSecretName . }}
                  key: {{ tpl .Values.postconfirm.database.user.existingSecretKey . }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.postconfirm.database.password.existingSecretName . }}
                  key: {{ tpl .Values.postconfirm.database.password.existingSecretKey . }}
            - name: MAIL_TEMPLATE
              value: /app/confirm.email.mustache
            - name: SMTP_HOST
              value: {{ .Values.postconfirm.smtp_host }}
            - name: SMTP_PORT
              value: '{{ .Values.postconfirm.smtp_port }}'
            - name: REMAIL_SENDER
              value: {{ .Values.postconfirm.remail_sender }}
            - name: MAIL_ADMIN
              value: {{ .Values.postconfirm.mail_admin }}

          ports:
            - name: postconfirm
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: postconfirm-template
              mountPath: /app/etc/confirm.email.mustache
              subPath: confirm.email.mustache
            - name: hash-key
              mountPath: /app/etc/key
              subPath: key
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: postconfirm-template
          configMap:
            name: postconfirm-template
        - name: hash-key
          secret:
            secretName: {{ .Values.postconfirm.hashkey.existingSecretName }}
            items:
              - key: {{ .Values.postconfirm.hashkey.existingSecretKey }}
                path: key
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
