{{- if .Values.secret_smtp.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_smtp.name }}
type: Opaque
data:
  username: {{ .Values.secret_smtp.data.username | b64enc }}
  password: {{ .Values.secret_smtp.data.password | b64enc }}
{{- end }}
